name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: CheckOut_Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKERS_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Iniciando login"
        docker login -u $secrets.DOCKERS_USER -p $secrets.DOCKER_PASSWORD
        echo "Fin del login"
        
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
